## Multiple Linear Regression using skLearn

### Import the libs

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

### Load the data

In [3]:
data = pd.read_csv('../data/1_02_multiple_linear_regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

### Create the regression

#### Declare the dependend and independent variables

In [7]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

#### Regression itself

In [10]:
reg = LinearRegression()
reg.fit(x, y)

LinearRegression()

#### Interpreting the results
First, we display the coefficients and intercept of our model.<br/>
The results below are the same as the ones provided by the 'StatsModels summary' (done in a previous practice).

In [12]:
reg.coef_       # It shows the coefficient of the SAT score and coefficient of the 'Rand 1,2,3' variable.
                # They are ordered in the way we fed them.

array([ 0.00165354, -0.00826982])

In [14]:
reg.intercept_  # It shows that the intercept of this model is 0.296.

0.29603261264909486

#### Calculating the R-squared
R-squared is one of the common measure of goodness of fit. It helps evaluating how well linear regressions fare and compare.

In [16]:
reg.score(x, y)

0.4066811952814283

#### The formula for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

where: n = number of observations (84), p = number of predictors (2)

In [17]:
x.shape

(84, 2)

In [19]:
r2 = reg.score(x, y)
n = x.shape[0]
p = x.shape[1]
adj_r2 = 1 - (1-r2) * (n-1) / (n-p-1)
adj_r2

0.3920313482513401

#### Feature Selection
We now determine which independent variables are bringing value into the model and exclude the other ones.<br/>
If a variable has a p-value > 0.05, then we can disregard it.

In [21]:
from sklearn.feature_selection import f_regression

In [23]:
f_regression(x, y)       # In its output, 1st array has F-statistics, 2nd array has p-values.

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [26]:
p_values = f_regression(x, y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [29]:
p_values.round(3)        # Rounded with just 3 digits after the dot, we have the p-values for SAT and 'Rand 1,2,3'.
                         # Thus, we can easily conclude that SAT is a useful variable, while 'Rand 1,2,3' is useless.

array([0.   , 0.676])

Note that F-regression might be too simplistic for more complicated problems, since the p-values generated from running the simple linear regressions do not reflect the interconnection of the features in our multiple linear regression.

### Creating a summary table

In [32]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [37]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [38]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676